# Build system: Taskfile (replaced legacy CMake)
version: "3"

vars:
  BIN_DIR: build/bin
  SERVER_BIN: "{{.BIN_DIR}}/server"
  DB_DIR: build/db
  DB_PATH: build/db/pickleicious.db
  MIGRATIONS_DIR: internal/db/migrations

tasks:
  generate:
    desc: Generate templ and sqlc code
    cmds:
      - templ generate
      - cmd: bash -c "cd internal/db && sqlc generate"
  generate-sqlc:
    desc: Generate sqlc code
    cmds:
      - cmd: bash -c "cd internal/db && sqlc generate"

  build:
    desc: Build the server binary
    deps:
      - generate
      - static_assets
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.SERVER_BIN}} ./cmd/server

  build:prod:
    desc: Build the server binary for production
    deps:
      - generate
      - static_assets
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags "-s -w" -o {{.SERVER_BIN}} ./cmd/server

  test:
    desc: Run Go tests
    deps:
      - generate-sqlc
    cmds:
      - go test ./...

  css:
    desc: Build Tailwind CSS
    dir: web
    cmds:
      - mkdir -p ./static/css
      - npx tailwindcss -i ./styles/input.css -o ./static/css/main.css

  static_assets:
    desc: Copy static assets into the build output directory
    deps:
      - css
    cmds:
      - mkdir -p {{.BIN_DIR}}/static
      - cp -R web/static/. {{.BIN_DIR}}/static/

  db:migrate:
    desc: Run database migrations with dbmigrate
    cmds:
      - mkdir -p {{.DB_DIR}}
      - go run cmd/tools/dbmigrate/main.go -command up -db {{.DB_PATH}} -migrations {{.MIGRATIONS_DIR}}

  db:reset:
    desc: Reset the database and re-run migrations
    cmds:
      - rm -f {{.DB_PATH}}
      - task: db:migrate

  dev:
    desc: Run the dev server without file watching
    env:
      STATIC_DIR: web/static
    deps:
      - generate
      - css
      - db:migrate
    cmds:
      - go run ./cmd/server

  dev:watch:
    desc: Run the dev server with Air
    env:
      STATIC_DIR: web/static
    deps:
      - generate
      - css
      - db:migrate
    cmds:
      - air -c .air.toml

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.SERVER_BIN}}
      - rm -rf {{.BIN_DIR}}/static
      - rm -rf build/tmp {{.DB_DIR}}
